# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev-tryout',
                'doc_host': 'https://jemma-nelson.github.io',
                'git_url': 'https://github.com/jemma-nelson/nbdev-tryout',
                'lib_path': 'nbdev_tryout'},
  'syms': {'nbdev_tryout.core': {'nbdev_tryout.core.foo': ('core.html#foo', 'nbdev_tryout/core.py')}}}